# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: compute.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'compute.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcompute.proto\x12\x07\x63ompute\"$\n\x11SumSquaresRequest\x12\x0f\n\x07numbers\x18\x01 \x03(\x05\"$\n\x12SumSquaresResponse\x12\x0e\n\x06result\x18\x01 \x01(\x03\x32W\n\x0e\x43omputeService\x12\x45\n\nSumSquares\x12\x1a.compute.SumSquaresRequest\x1a\x1b.compute.SumSquaresResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compute_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMSQUARESREQUEST']._serialized_start=26
  _globals['_SUMSQUARESREQUEST']._serialized_end=62
  _globals['_SUMSQUARESRESPONSE']._serialized_start=64
  _globals['_SUMSQUARESRESPONSE']._serialized_end=100
  _globals['_COMPUTESERVICE']._serialized_start=102
  _globals['_COMPUTESERVICE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
